[package]
name = "bbb-record-parser"
version = "0.1.0"
authors = [ "Valentin Popov <info@valentineus.link>" ]
edition = "2018"

[dependencies]
clap = { version = "2.32.0", features = [ "yaml" ] }
rustc-serialize = "0.3.24"
xml-rs = "0.8.0"